spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: transaction-group-id
    topics:
      anti-fraud: anti-fraud-topic
      transaction: transaction-topic

  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres?schema=public
    username: postgres
    password: postgres
    pool:
      initial-size: 10
      max-size: 50
      max-idle-time: 30m
      max-acquire-time: 5s
      validation-query: SELECT 1

