CREATE TABLE IF NOT EXISTS public.transactions (
    id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    transaction_external_id varchar(36) NOT NULL,
    account_external_id_debit varchar(36) NOT NULL,
    account_external_id_credit varchar(36) NOT NULL,
    type varchar(10) NOT NULL,
    status varchar(10) NOT NULL,
    updated_at timestamp NULL,
    created_at timestamp NOT NULL,
    value numeric(10, 2) NOT NULL,
    version int4 NOT NULL DEFAULT 0,
    CONSTRAINT transactions_pkey PRIMARY KEY (id)
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_transaction_external_id
    ON transactions(transaction_external_id);

CREATE UNIQUE INDEX IF NOT EXISTS idx_debit_credit_type_pending
    ON transactions(account_external_id_debit, account_external_id_credit, type)
    WHERE status = 'PENDING';